{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "myBuzzn App API",
        "description": "An app to investigate your power consumption habits for BUZZN customers."
    },
    "paths": {
        "/assets/group-profile-pictures": {
            "get": {
                "summary": "Shows the profile pictures of the user's group.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "$ref": "#/definitions/User/properties/id"
                                    },
                                    "avatar": {
                                        "$ref": "#/definitions/User/properties/avatar"
                                    }
                                }
                            }
                        }
                    },
                    "206": {
                        "description": "group member query/avatar query fails",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorName": {
                                    "type": "string"
                                },
                                "errorDescription": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "group member query/avatar query fails",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorName": {
                                    "type": "string"
                                },
                                "errorDescription": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "tags": [
                    "group profile pictures"
                ],
                "produces": [
                    "array"
                ],
                "operationId": "showGroupProfilePictures"
            }
        },
        "/individual-consumption-history": {
            "get": {
                "summary": "Shows the history of power consumption from the given starting point of a user.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "energy": {
                                    "description": "A dictionary (JSON object) with each meter reading (\u03bcWh/10) mapped to its timestamp.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    },
                                    "example": {
                                        "2020-01-15 10:00:04": 2180256872214000,
                                        "2020-01-15 10:01:10": 2180256872214000
                                    }
                                },
                                "power": {
                                    "description": "A dictionary (JSON object) with each power consumption (mW) mapped to its timestamp.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    },
                                    "example": {
                                        "2020-01-15 10:00:04": 0,
                                        "2020-01-15 10:01:10": 0
                                    }
                                }
                            }
                        }
                    },
                    "206": {
                        "description": "No history available"
                    }
                },
                "parameters": [
                    {
                        "name": "begin",
                        "in": "query",
                        "description": "Start time of consumption as unix timestamp. Default is yesterday at 00:00:00 am.",
                        "required": false,
                        "type": "integer"
                    }
                ],
                "tags": [
                    "consumption history"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "userConsumptionHistory"
            }
        },
        "/individual-global-challenge": {
            "get": {
                "summary": "Shows the individual saving prognosis for today in \u00b5Wh/10 and the individual baseline in \u00b5Wh/10.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "saving": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number",
                                        "format": "float"
                                    }
                                },
                                "baseline": {
                                    "$ref": "#/definitions/User/properties/baseline"
                                }
                            },
                            "example": {
                                "saving": {
                                    "2020-01-15 10:01:10": 3148577026610.7812
                                },
                                "baseline": 53011346257574
                            }
                        }
                    },
                    "206": {
                        "description": "No history available"
                    }
                },
                "tags": [
                    "global challenge"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "individualGlobalChallenge"
            }
        },
        "/community-global-challenge": {
            "get": {
                "summary": "Shows the community saving prognosis for today in \u00b5Wh/10",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number",
                                "format": "float"
                            },
                            "example": {
                                "2020-02-13 16:20:21": 85184267259376.5
                            }
                        }
                    },
                    "206": {
                        "description": "no history available"
                    }
                },
                "tags": [
                    "global challenge"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "communityGlobalChallenge"
            }
        },
        "/group-consumption-history": {
            "get": {
                "summary": "Shows the history of power consumption of a group.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "consumed_energy": {
                                    "description": "A dictionary (JSON object) with the first and the latest meter reading (\u03bcWh/10) of the day mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    },
                                    "example": {
                                        "2020-01-15 00:00:04": "2180256872214000,",
                                        "2020-01-15 00:47:10": 2180256872214000
                                    }
                                },
                                "consumed_power": {
                                    "description": "A dictionary (JSON object) with average power consumptions (mW) of 15 minute timeframes mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number",
                                        "format": "float"
                                    },
                                    "example": {
                                        "2020-01-15 00:15:00": "224550.0,",
                                        "2020-01-15 00:30:00": "232000.0,",
                                        "2020-01-15 00:45:00": 227630.0
                                    }
                                },
                                "group_users": {
                                    "description": "A dictionary (JSON objects) with the first and the latest meter reading (\u03bcWh/10) of the day and average power consumption values (mW) of 15 minutes timeframes of each group user mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "object",
                                        "properties": {
                                            "energy": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "integer"
                                                }
                                            },
                                            "power": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "1": {
                                            "energy": {
                                                "2020-01-15 00:00:04": "2180256872214000,",
                                                "2020-01-15 00:47:10": 2180256872214000
                                            },
                                            "power": {
                                                "2020-01-15 00:15:00": "224550.0,",
                                                "2020-01-15 00:30:00": "232000.0,",
                                                "2020-01-15 00:45:00": 227630.0
                                            }
                                        },
                                        "2": {
                                            "energy": {
                                                "2020-01-15 00:00:04": "2180256872214000,",
                                                "2020-01-15 00:47:10": 2180256872214000
                                            },
                                            "power": {
                                                "2020-01-15 00:15:00": "224550.0,",
                                                "2020-01-15 00:30:00": "232000.0,",
                                                "2020-01-15 00:45:00": 227630.0
                                            }
                                        }
                                    }
                                },
                                "produced_first_meter_energy": {
                                    "description": "A dictionary (JSON object) with the first and the latest meter reading (\u03bcWh/10) of the day mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    },
                                    "example": {
                                        "2020-01-15 00:00:04": "2180256872214000,",
                                        "2020-01-15 00:47:10": 2180256872214000
                                    }
                                },
                                "produced_first_meter_power": {
                                    "description": "A dictionary (JSON object) with average power productions (mW) of 15 minute timeframes mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number",
                                        "format": "float"
                                    },
                                    "example": {
                                        "2020-01-15 00:15:00": "224550.0,",
                                        "2020-01-15 00:30:00": "232000.0,",
                                        "2020-01-15 00:45:00": 227630.0
                                    }
                                },
                                "produced_second_meter_energy": {
                                    "description": "A dictionary (JSON object) with the first and the latest meter reading (\u03bcWh/10) of the day mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    },
                                    "example": {
                                        "2020-01-15 00:00:04": "2180256872214000,",
                                        "2020-01-15 00:47:10": 2180256872214000
                                    }
                                },
                                "produced_second_meter_power": {
                                    "description": "A dictionary (JSON object) with average power productions (mW) of 15 minute timeframes mapped to their timestamps.",
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "number",
                                        "format": "float"
                                    },
                                    "example": {
                                        "2020-01-15 00:15:00": "224550.0,",
                                        "2020-01-15 00:30:00": "232000.0,",
                                        "2020-01-15 00:45:00": 227630.0
                                    }
                                }
                            }
                        }
                    },
                    "206": {
                        "description": "No history available"
                    }
                },
                "tags": [
                    "consumption history"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "groupConsumptionHistory"
            }
        },
        "/individual-disaggregation": {
            "get": {
                "summary": "Shows the power curve disaggregation from the given starting point for a user.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "integer"
                                }
                            },
                            "example": {
                                "2020-01-15 10:01:10": {
                                    "Waschmaschine-1": 0,
                                    "Sp\u00fclmaschine-1": 0,
                                    "Durchlauferhitzer-2": 0,
                                    "Durchlauferhitzer-3": 0,
                                    "Grundlast-1": 2500000,
                                    "Durchlauferhitzer-1": 0
                                }
                            }
                        }
                    },
                    "206": {
                        "description": "No history available"
                    }
                },
                "parameters": [
                    {
                        "name": "begin",
                        "in": "query",
                        "description": "Start time of disaggregation as unix timestamp. Default is two days ago at 00:00:00 am.",
                        "required": false,
                        "type": "integer"
                    }
                ],
                "tags": [
                    "disaggregation"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "individualDisaggregation"
            }
        },
        "/per-capita-consumption": {
            "get": {
                "summary": "Shows the annualized moving average of the user's per capita consumption for today in kWh.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            },
                            "example": {
                                "2020-03-10 17:08:24": 396932
                            }
                        }
                    },
                    "206": {
                        "description": "No value available"
                    }
                },
                "tags": [
                    "per capita consumption"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "showPerCapitaConsumption"
            }
        },
        "/group-disaggregation": {
            "get": {
                "summary": "Shows the power curve disaggregation from the given starting point for a  group.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "integer"
                                }
                            },
                            "example": {
                                "2020-01-15 10:01:10": {
                                    "Waschmaschine-1": 0,
                                    "Sp\u00fclmaschine-1": 0,
                                    "Durchlauferhitzer-2": 0,
                                    "Durchlauferhitzer-3": 0,
                                    "Grundlast-1": 2500000,
                                    "Durchlauferhitzer-1": 0
                                }
                            }
                        }
                    },
                    "206": {
                        "description": "No history available"
                    }
                },
                "parameters": [
                    {
                        "name": "begin",
                        "in": "query",
                        "description": "Start time of disaggregation as unix timestamp. Default is two days ago at 00:00:00 am.",
                        "required": false,
                        "type": "integer"
                    }
                ],
                "tags": [
                    "disaggregation"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "groupDisaggregation"
            }
        },
        "/set-password": {
            "post": {
                "summary": "Sets an initial password. Does not require the user to be logged in.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "password passes the validation"
                    },
                    "400": {
                        "description": "password fails the validation or the token is invalid",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorName": {
                                    "type": "string"
                                },
                                "errorDescription": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "password to set and user token",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "tags": [
                    "profile"
                ],
                "consumes": [
                    "application/json"
                ],
                "operationId": "setPassword"
            }
        },
        "/profile": {
            "get": {
                "summary": "Gets the user's profile.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "$ref": "#/definitions/User/properties/id"
                                },
                                "name": {
                                    "$ref": "#/definitions/User/properties/name"
                                },
                                "firstName": {
                                    "$ref": "#/definitions/User/properties/first_name"
                                },
                                "nick": {
                                    "$ref": "#/definitions/User/properties/nick"
                                },
                                "flatSize": {
                                    "$ref": "#/definitions/User/properties/flat_size"
                                },
                                "inhabitants": {
                                    "$ref": "#/definitions/User/properties/inhabitants"
                                },
                                "groupAddress": {
                                    "$ref": "#/definitions/Group/properties/name"
                                },
                                "mail": {
                                    "$ref": "#/definitions/User/properties/mail"
                                },
                                "avatar": {
                                    "$ref": "#/definitions/User/properties/avatar"
                                },
                                "meterId": {
                                    "$ref": "#/definitions/User/properties/meter_id"
                                },
                                "registration_date": {
                                    "$ref": "#/definitions/User/properties/registration_date"
                                },
                                "baseline_state": {
                                    "$ref": "#/definitions/User/properties/baseline_state"
                                }
                            }
                        }
                    }
                },
                "tags": [
                    "profile"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "getProfile"
            },
            "put": {
                "summary": "Sets the user's profile stats.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "validation passed"
                    },
                    "400": {
                        "description": "validation failed",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorName": {
                                    "type": "string"
                                },
                                "errorDescription": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "profile stats to update",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "flatSize": {
                                    "type": "number",
                                    "format": "float"
                                },
                                "inhabitants": {
                                    "type": "integer"
                                },
                                "nick": {
                                    "type": "string"
                                },
                                "avatar": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "tags": [
                    "profile"
                ],
                "consumes": [
                    "application/json"
                ],
                "operationId": "updateProfile"
            }
        },
        "/login": {
            "post": {
                "summary": "Performs a login for the given user credentials.",
                "description": "",
                "responses": {
                    "200": {
                        "description": "successful login",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "sessionToken": {
                                    "type": "string",
                                    "description": "The session token."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "username does not exist or password is incorrect",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorName": {
                                    "type": "string"
                                },
                                "errorDescription": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "user credentials",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "user": {
                                    "type": "string",
                                    "description": "The account's mail address."
                                },
                                "password": {
                                    "type": "string",
                                    "description": "The account's password."
                                }
                            },
                            "example": {
                                "user": "user@example.com",
                                "password": "example_password"
                            }
                        }
                    }
                ],
                "tags": [
                    "user login"
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "operationId": "login"
            }
        }
    },
    "definitions": {
        "User": {
            "properties": {
                "id": {
                    "type": "integer",
                    "description": "The user's id."
                },
                "gender": {
                    "type": "string",
                    "description": "The user's gender",
                    "enum": [
                        "MALE",
                        "FEMALE"
                    ]
                },
                "first_name": {
                    "type": "string",
                    "description": "The user's first name.",
                    "maxLength": 33
                },
                "name": {
                    "type": "string",
                    "description": "The user's name.",
                    "maxLength": 33
                },
                "nick": {
                    "type": "string",
                    "maxLength": 33,
                    "description": "The user's nick name."
                },
                "mail": {
                    "type": "string",
                    "maxLength": 33,
                    "description": "The user's mail address."
                },
                "activation_token": {
                    "type": "string",
                    "maxLength": 33,
                    "description": "The user's activation token"
                },
                "password": {
                    "type": "string",
                    "maxLength": 333,
                    "description": "The user's password"
                },
                "state": {
                    "type": "string",
                    "description": "The user account's state in its lifecycle",
                    "enum": [
                        "ACTIVATION_PENDING",
                        "PASSWORT_RESET_PENDING",
                        "ACTIVE",
                        "DEACTIVATED"
                    ]
                },
                "role": {
                    "type": "string",
                    "description": "The role of a user account. This may privilege the user for specific actions.",
                    "enum": [
                        "LOCAL_POWER_TAKER",
                        "ADMINISTRATOR"
                    ]
                },
                "meter_id": {
                    "type": "string",
                    "description": "The id of the user's meter.",
                    "maxLength": 32
                },
                "inhabitants": {
                    "type": "integer",
                    "description": "The number of people living in the flat."
                },
                "flat_size": {
                    "type": "number",
                    "format": "float",
                    "description": "The user's flat size in m^2."
                },
                "group_id": {
                    "$ref": "#/definitions/Group/properties/id"
                },
                "password_reset_token": {
                    "type": "string",
                    "maxLength": 33
                },
                "password_reset_token_expires": {
                    "type": "string",
                    "format": "date-time"
                },
                "avatar": {
                    "type": "string",
                    "format": "binary",
                    "description": "The user's avatar encoded in base64."
                },
                "baseline": {
                    "type": "integer",
                    "description": "The user's baseline."
                },
                "baseline_state": {
                    "type": "string",
                    "description": "the user's baseline state",
                    "enum": [
                        "READY",
                        "WAITING_FOR_DATA",
                        "NO_READINGS_AVAILABLE"
                    ]
                },
                "registration_date": {
                    "type": "string",
                    "format": "date-time",
                    "description": "The user's registration date."
                }
            }
        },
        "Group": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "group_meter_id": {
                    "type": "string",
                    "maxLength": 32
                },
                "group_production_meter_id_first": {
                    "type": "string",
                    "maxLength": 32
                },
                "group_production_meter_id_second": {
                    "type": "string",
                    "maxLength": 32
                }
            }
        }
    }
}